fix(upgrader): Wrong digest pulled from docker pull (#270)
The digest used from docker pull/inspect is incorrect.

Pull the digest from the registry V2 api, and get the latest available tag from the v1 api. This will ensure that the correct digest is passed on to the WORKSPACE file, rather than the digest of the manifest itself.

The selection of the latest tag has been split out to its own action to reduce the complexity in the digest action.

diff --git a/.github/actions/docker-image-digest/action.yml b/.github/actions/docker-image-digest/action.yml
--- a/.github/actions/docker-image-digest/action.yml
+++ b/.github/actions/docker-image-digest/action.yml
@@ -7,6 +7,9 @@ inputs:
   image:
     description: 'The namespace of the image'
     required: true
+  architecture:
+    description: 'The architecture of the image'
+    required: true
   tag:
     description: 'The tag of the image'
     required: true
@@ -14,19 +17,33 @@ outputs:
   image-digest:
     description: "The image digest"
     value: ${{ steps.action.outputs.image-digest }}
-  image-tag:
-    description: "The image tag"
-    value: ${{ steps.action.outputs.image-tag }}
 runs:
   using: "composite"
   steps:
     - id: action
       shell: bash
       run: |
-          request_url="https://${{ inputs.url }}/v1/repositories/${{ inputs.image }}/tags"
-          echo "Request: ${request_url}"
-          latest=$(wget -q "${request_url}" -O - | tr -d '[]" ' | tr '}' '\n' | awk -F: '{print $3}' | grep '${{ inputs.tag }}' | sort -rn | head -n1)
-          docker pull ${{ inputs.image }}:${latest}
-          image_digest=`docker inspect --format='{{index .RepoDigests 0}}' ${{ inputs.image }}:${latest} | cut -d'@' -f2`
-          echo "::set-output name=image-digest::$image_digest"
-          echo "::set-output name=image-tag::$latest"
+        request_url="https://${{ inputs.url }}/v2/repositories/${{ inputs.image }}/tags"
+        digest=""
+        for i in $(seq 1 10); do
+            echo "Request: $request_url"
+            response=$(wget -q "${request_url}" -O -)
+            next_url=`echo $response | jq -r '.next'`
+
+            manifest=`echo $response | jq -r '.results | .[] | select(.name=="${{ inputs.tag }}")'`
+            if [[ -n "$manifest" ]]; then
+                echo "Found manifest for tag: ${{ inputs.tag }}"
+                image=`echo $manifest | jq -r '.images | .[] | select(.architecture=="${{ inputs.architecture }}")'`
+                
+                echo $image | jq -r "."
+                digest=`echo $image | jq -r '.digest'`                
+                break;
+            fi
+
+            request_url="$next_url"
+        done
+        echo "::set-output name=image-digest::$digest"
+        if [[ -z "$digest" ]]; then
+            echo "Failed to find digest for $latest"
+            exit 1
+        fi
